# traefik.yml
entryPoints:
  web:
    address: ":8080"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true
  insecure: true  # 允许通过HTTP访问Dashboard