apiVersion: v1
kind: Service
metadata:
  name: tcm-frontend-service
spec:
  selector:
    app: tcm-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: tcm-backend-service
spec:
  selector:
    app: tcm-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tcm-nlp-service
spec:
  selector:
    app: tcm-nlp-service
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tcm-redis-service
spec:
  selector:
    app: tcm-redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tcm-gateway-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: tcm-gateway
  ports:
  - name: web
    port: 8000
    targetPort: 8080
  - name: websecure
    port: 8443
    targetPort: 443
  type: LoadBalancer 